---
- name: Install Vim, the MySQL client, Ruby via RVM, and Nginx
  hosts: footprints_local
  remote_user: root
  become: yes

  roles:
    - common
    - vim
    - mysql
    - { role: rvm_io.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.1.5'],
        rvm1_install_flags: '--auto-dotfiles', # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,     # Set to system location
        rvm1_user: root                        # Need root account to access system location
      }
    - footprints
    - nginx
